//! End-to-end Groth16 verification test using a real snarkjs proof.
//!
//! Circuit: multiply(a, b) -> c where c = a * b
//! Inputs: a=3, b=7 => c=21
//! Public input: c=21 (0x15)
//!
//! The proof was generated by snarkjs with a BN254 (bn128) trusted setup.

extern crate alloc;

use verifier_test::bn254::fq::Fq;
use verifier_test::bn254::fr::Fr;
use verifier_test::bn254::fq2::Fq2;
use verifier_test::bn254::g1::G1Affine;
use verifier_test::bn254::g2::G2Affine;
use verifier_test::bn254::pairing;
use verifier_test::bn254::fq12;
use verifier_test::groth16::{self, Proof, VerificationKey};

/// Parse a 0x-prefixed hex string into a 32-byte big-endian array
fn hex_to_bytes32(s: &str) -> [u8; 32] {
    let s = s.strip_prefix("0x").unwrap_or(s);
    let bytes = hex::decode(s).expect("invalid hex");
    let mut arr = [0u8; 32];
    // Left-pad with zeros if needed
    let start = 32 - bytes.len();
    arr[start..].copy_from_slice(&bytes);
    arr
}

fn make_g1(x_hex: &str, y_hex: &str) -> G1Affine {
    let x = Fq::from_bytes_be(&hex_to_bytes32(x_hex));
    let y = Fq::from_bytes_be(&hex_to_bytes32(y_hex));
    G1Affine { x, y, infinity: false }
}

fn make_g2(x_c0_hex: &str, x_c1_hex: &str, y_c0_hex: &str, y_c1_hex: &str) -> G2Affine {
    let x = Fq2::new(
        Fq::from_bytes_be(&hex_to_bytes32(x_c0_hex)),
        Fq::from_bytes_be(&hex_to_bytes32(x_c1_hex)),
    );
    let y = Fq2::new(
        Fq::from_bytes_be(&hex_to_bytes32(y_c0_hex)),
        Fq::from_bytes_be(&hex_to_bytes32(y_c1_hex)),
    );
    G2Affine { x, y, infinity: false }
}

// ======================================================================
// Test: Basic field arithmetic
// ======================================================================

#[test]
fn test_fq_basic_arithmetic() {
    use verifier_test::bn254::fq;

    let a = Fq::from_u64(42);
    let b = Fq::from_u64(58);

    // Addition
    let c = a.add(&b);
    assert_eq!(c, Fq::from_u64(100));

    // Subtraction
    let d = c.sub(&b);
    assert_eq!(d, a);

    // Multiplication
    let e = Fq::from_u64(7).mul(&Fq::from_u64(6));
    assert_eq!(e, Fq::from_u64(42));

    // Negation
    let neg_a = a.neg();
    assert!(a.add(&neg_a).is_zero());

    // Inverse
    let a_inv = a.inv().unwrap();
    assert_eq!(a.mul(&a_inv), fq::ONE);
}

#[test]
fn test_fr_basic_arithmetic() {
    use verifier_test::bn254::fr;

    let a = Fr::from_u64(42);
    let b = Fr::from_u64(58);

    let c = a.add(&b);
    assert_eq!(c, Fr::from_u64(100));

    let d = c.sub(&b);
    assert_eq!(d, a);

    let e = Fr::from_u64(7).mul(&Fr::from_u64(6));
    assert_eq!(e, Fr::from_u64(42));

    let a_inv = a.inv().unwrap();
    assert_eq!(a.mul(&a_inv), fr::ONE);
}

#[test]
fn test_fq2_arithmetic() {
    use verifier_test::bn254::fq2;

    let a = Fq2::new(Fq::from_u64(3), Fq::from_u64(4));
    let b = Fq2::new(Fq::from_u64(5), Fq::from_u64(7));

    // Mul then inv
    let a_inv = a.inv().unwrap();
    assert_eq!(a.mul(&a_inv), fq2::ONE);

    // Square == mul(self)
    let sq = a.square();
    let mm = a.mul(&a);
    assert_eq!(sq, mm);

    // Non-residue multiplication consistency
    let nr = a.mul_by_nonresidue();
    let nine_plus_u = Fq2::new(Fq::from_u64(9), Fq::from_u64(1));
    let manual = a.mul(&nine_plus_u);
    assert_eq!(nr, manual);
}

// ======================================================================
// Test: G1 curve operations
// ======================================================================

#[test]
fn test_g1_on_curve() {
    // The standard BN254 G1 generator is (1, 2)
    let gen = make_g1(
        "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x0000000000000000000000000000000000000000000000000000000000000002",
    );
    assert!(gen.is_on_curve(), "G1 generator (1,2) must be on curve y^2 = x^3 + 3");
}

#[test]
fn test_g1_double_and_add() {
    let gen = make_g1(
        "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x0000000000000000000000000000000000000000000000000000000000000002",
    );

    let g_proj = gen.to_projective();

    // 2G
    let g2 = g_proj.double();
    let g2_aff = g2.to_affine();
    assert!(g2_aff.is_on_curve(), "2G must be on curve");

    // G + G should equal 2G
    let g_plus_g = g_proj.add_projective(&g_proj);
    let g_plus_g_aff = g_plus_g.to_affine();
    assert_eq!(g2_aff, g_plus_g_aff, "G + G must equal 2G");

    // 3G = 2G + G
    let g3 = g2.add_projective(&g_proj);
    let g3_aff = g3.to_affine();
    assert!(g3_aff.is_on_curve(), "3G must be on curve");
}

#[test]
fn test_g1_scalar_mul_identity() {
    let gen = make_g1(
        "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x0000000000000000000000000000000000000000000000000000000000000002",
    );

    // 1 * G = G
    let scalar_one = [1u64, 0, 0, 0];
    let result = gen.to_projective().scalar_mul(&scalar_one).to_affine();
    assert_eq!(result, gen, "1 * G must equal G");
}

// ======================================================================
// Test: G2 curve operations
// ======================================================================

#[test]
fn test_g2_generator_on_curve() {
    // Standard BN254 G2 generator
    let gen = make_g2(
        "0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed",
        "0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2",
        "0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa",
        "0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b",
    );
    assert!(gen.is_on_curve(), "G2 generator must be on twist curve");
}

// ======================================================================
// Test: Pairing properties
// ======================================================================

#[test]
fn test_pairing_identity() {
    let p = G1Affine::identity();
    let q = G2Affine::identity();
    let result = pairing::pairing(&p, &q);
    assert!(result.is_one(), "e(O, O) must be 1");
}

#[test]
fn test_pairing_g1_identity() {
    let p = G1Affine::identity();
    let q = make_g2(
        "0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed",
        "0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2",
        "0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa",
        "0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b",
    );
    let result = pairing::pairing(&p, &q);
    assert!(result.is_one(), "e(O, Q) must be 1");
}

#[test]
fn test_pairing_bilinearity() {
    // Bilinearity check: e(aP, Q) = e(P, Q)^a
    // Using G1 generator P = (1, 2) and G2 generator Q
    let p_gen = make_g1(
        "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x0000000000000000000000000000000000000000000000000000000000000002",
    );
    let q_gen = make_g2(
        "0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed",
        "0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2",
        "0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa",
        "0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b",
    );

    // Compute 2P
    let two_p = p_gen.to_projective().double().to_affine();

    // e(2P, Q)
    let lhs = pairing::pairing(&two_p, &q_gen);

    // e(P, Q)^2
    let e_pq = pairing::pairing(&p_gen, &q_gen);
    let rhs = e_pq.mul(&e_pq);

    assert_eq!(lhs, rhs, "Bilinearity: e(2P, Q) must equal e(P, Q)^2");
}

#[test]
fn test_pairing_check_simple() {
    // e(P, Q) * e(-P, Q) = 1
    let p_gen = make_g1(
        "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x0000000000000000000000000000000000000000000000000000000000000002",
    );
    let neg_p = p_gen.neg();
    let q_gen = make_g2(
        "0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed",
        "0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2",
        "0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa",
        "0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b",
    );

    let result = pairing::pairing_check(&[
        (p_gen, q_gen),
        (neg_p, q_gen),
    ]);
    assert!(result, "e(P,Q) * e(-P,Q) must equal 1");
}

// ======================================================================
// Test: Frobenius maps
// ======================================================================

#[test]
fn test_fq12_frobenius_identity() {
    // f^{q^12} = f for elements in Fq12
    // Since frobenius_map(12) should be identity, and our implementation uses mod 12,
    // frobenius_map(0) should be identity.
    let f = fq12::ONE;
    assert_eq!(f.frobenius_map(0), f);
}

// ======================================================================
// Test: Groth16 verification with real snarkjs proof
// ======================================================================

#[test]
fn test_groth16_verify_snarkjs_proof() {
    // Test vectors from snarkjs:
    // Circuit: multiply(a, b) -> c where a=3, b=7, c=21
    // Public input: 21 (0x15)

    // Proof elements
    let pi_a = make_g1(
        "0x22497f4b7fc3663ada2a543dc823a550b9fdc4ec94d907ceaa64a020d5ee412b",
        "0x0dc9219e024d84eeda8cdcb6898fdcc4ad4c58d6da8bc306e4dcbe9b6c4105c9",
    );
    let pi_b = make_g2(
        "0x2a281d87d584a367ef2dfe58f651d02fc77389c80ad6b174035781d302cfdb0f",
        "0x0a0d05fcad3d1c3aba342da5e208f7f9e879dec4d49d06714140b7f7d9358a93",
        "0x0952ac340f11e63915a61e57798893a501f4d3c5c61be37b6198d19e457cacd9",
        "0x2020f6d6f8bb4b763552eb522f30d6b3b8eb3b070d3c9e9cc1c1342475ff3e4d",
    );
    let pi_c = make_g1(
        "0x1de02837e822e9721bd765b011a70575d9d1b7b7754b472868d2b5947f0b1386",
        "0x11ef1ba4c58a972d55a8f178fb676016d5859ef6d6177c85ef46a4824b858d2b",
    );

    // Verification key
    let alpha_g1 = make_g1(
        "0x0207bcca97e48d0b3faff5686c7642da1167b2992e9991fa7414849bab22be6b",
        "0x03d5ca4adbe4c889fcc4c8ec6bb7d84edfd43b9dfde80e0e806850a7b8c261b0",
    );
    let beta_g2 = make_g2(
        "0x2b701e77a7fd6260f70797766ddfcc241a7e14b33f6e80781835617ad5ff00f0",
        "0x13d810ac51b337a8aea7a4c0f1a4a5c0c75dfdeb6399b7138e42663487d0bf89",
        "0x077ec078585b253705517ce80d0fb6b9d2505dd72e2e8d9fd6caaa41b575c038",
        "0x0ccb8c61aa8854f4b26938c646a9ca3a40df9ec4ba76de3656f79dad494ab78a",
    );
    let gamma_g2 = make_g2(
        "0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed",
        "0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2",
        "0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa",
        "0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b",
    );
    let delta_g2 = make_g2(
        "0x173a7e27e820c7068ee476711ec13ca99b6d8507e915dfea4fa596b0466d68d7",
        "0x2c9137e9512e299638457189533ad25d9223713243cb17ad52e71e54c19448b9",
        "0x0e6781c6b38ecde7ad1ab6b80809507aa05145a88890ca6cb03a183fa5e9304f",
        "0x20dc2fb25da814e1564bfc2bbc9bec2f3f60ff97513490614cc6055010718702",
    );
    let ic_0 = make_g1(
        "0x01522d43468d49817509d574163b326078c5e6436fbff0c2272138300ea97206",
        "0x1c085b8626b0634fdef26d034b1820fa1bc1ac74ae94631f7cdbf326a2bce5ef",
    );
    let ic_1 = make_g1(
        "0x1d0e33258732ed2db4c284d8ccdc126eb01fd6957fd5b86d989638be938c51df",
        "0x08a9117646ab2b08558de38b3e87c3d71dfa8b5866d765109bda11e345dbcb70",
    );

    // Validate all points are on their respective curves
    assert!(pi_a.is_on_curve(), "pi_a not on G1 curve");
    assert!(pi_b.is_on_curve(), "pi_b not on G2 curve");
    assert!(pi_c.is_on_curve(), "pi_c not on G1 curve");
    assert!(alpha_g1.is_on_curve(), "alpha not on G1 curve");
    assert!(beta_g2.is_on_curve(), "beta not on G2 curve");
    assert!(gamma_g2.is_on_curve(), "gamma not on G2 curve");
    assert!(delta_g2.is_on_curve(), "delta not on G2 curve");
    assert!(ic_0.is_on_curve(), "ic_0 not on G1 curve");
    assert!(ic_1.is_on_curve(), "ic_1 not on G1 curve");

    // Public input: 21
    let public_input = Fr::from_bytes_be(&hex_to_bytes32(
        "0x0000000000000000000000000000000000000000000000000000000000000015"
    ));

    let proof = Proof {
        a: pi_a,
        b: pi_b,
        c: pi_c,
    };

    let vk = VerificationKey {
        alpha_g1,
        beta_g2,
        gamma_g2,
        delta_g2,
        ic: vec![ic_0, ic_1],
    };

    let public_inputs = vec![public_input];

    // Run the Groth16 verification
    let result = groth16::verify(&vk, &proof, &public_inputs);
    assert!(result, "Groth16 verification must pass for valid proof!");
}

#[test]
fn test_groth16_reject_wrong_input() {
    // Same proof but wrong public input (22 instead of 21)
    // This should fail verification.

    let pi_a = make_g1(
        "0x22497f4b7fc3663ada2a543dc823a550b9fdc4ec94d907ceaa64a020d5ee412b",
        "0x0dc9219e024d84eeda8cdcb6898fdcc4ad4c58d6da8bc306e4dcbe9b6c4105c9",
    );
    let pi_b = make_g2(
        "0x2a281d87d584a367ef2dfe58f651d02fc77389c80ad6b174035781d302cfdb0f",
        "0x0a0d05fcad3d1c3aba342da5e208f7f9e879dec4d49d06714140b7f7d9358a93",
        "0x0952ac340f11e63915a61e57798893a501f4d3c5c61be37b6198d19e457cacd9",
        "0x2020f6d6f8bb4b763552eb522f30d6b3b8eb3b070d3c9e9cc1c1342475ff3e4d",
    );
    let pi_c = make_g1(
        "0x1de02837e822e9721bd765b011a70575d9d1b7b7754b472868d2b5947f0b1386",
        "0x11ef1ba4c58a972d55a8f178fb676016d5859ef6d6177c85ef46a4824b858d2b",
    );

    let alpha_g1 = make_g1(
        "0x0207bcca97e48d0b3faff5686c7642da1167b2992e9991fa7414849bab22be6b",
        "0x03d5ca4adbe4c889fcc4c8ec6bb7d84edfd43b9dfde80e0e806850a7b8c261b0",
    );
    let beta_g2 = make_g2(
        "0x2b701e77a7fd6260f70797766ddfcc241a7e14b33f6e80781835617ad5ff00f0",
        "0x13d810ac51b337a8aea7a4c0f1a4a5c0c75dfdeb6399b7138e42663487d0bf89",
        "0x077ec078585b253705517ce80d0fb6b9d2505dd72e2e8d9fd6caaa41b575c038",
        "0x0ccb8c61aa8854f4b26938c646a9ca3a40df9ec4ba76de3656f79dad494ab78a",
    );
    let gamma_g2 = make_g2(
        "0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed",
        "0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2",
        "0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa",
        "0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b",
    );
    let delta_g2 = make_g2(
        "0x173a7e27e820c7068ee476711ec13ca99b6d8507e915dfea4fa596b0466d68d7",
        "0x2c9137e9512e299638457189533ad25d9223713243cb17ad52e71e54c19448b9",
        "0x0e6781c6b38ecde7ad1ab6b80809507aa05145a88890ca6cb03a183fa5e9304f",
        "0x20dc2fb25da814e1564bfc2bbc9bec2f3f60ff97513490614cc6055010718702",
    );
    let ic_0 = make_g1(
        "0x01522d43468d49817509d574163b326078c5e6436fbff0c2272138300ea97206",
        "0x1c085b8626b0634fdef26d034b1820fa1bc1ac74ae94631f7cdbf326a2bce5ef",
    );
    let ic_1 = make_g1(
        "0x1d0e33258732ed2db4c284d8ccdc126eb01fd6957fd5b86d989638be938c51df",
        "0x08a9117646ab2b08558de38b3e87c3d71dfa8b5866d765109bda11e345dbcb70",
    );

    // WRONG public input: 22 instead of 21
    let wrong_input = Fr::from_bytes_be(&hex_to_bytes32(
        "0x0000000000000000000000000000000000000000000000000000000000000016"
    ));

    let proof = Proof {
        a: pi_a,
        b: pi_b,
        c: pi_c,
    };

    let vk = VerificationKey {
        alpha_g1,
        beta_g2,
        gamma_g2,
        delta_g2,
        ic: vec![ic_0, ic_1],
    };

    let public_inputs = vec![wrong_input];

    let result = groth16::verify(&vk, &proof, &public_inputs);
    assert!(!result, "Groth16 verification must FAIL for wrong public input!");
}
